### ISSUE TITLE
LaravelCaffeine doesnt seem to be working

### ISSUE THREAD

**Issue by kurtssmith** [GeneaLabs/laravel-caffeine#70] opened 2017-12-05 15:11 UTC
## Expected Behavior
I login and successfully redirected to the destination page. I logout and I am successfully redirected to the login page.  I then wait for a long time on the login page and then try to login and I get redirected to the destination page

## Acutal Behavior
I login and successfully redirected to the destination page. I logout and I am successfully redirected to the login page.  I then wait for a long time on the login page and then try to login and I get TokenMismatchException in VerifyCsrfToken.php line 68 

## Environment
- PHP Version: 5.6.15
- Laravel Version: 5.4.21
- LaravelCaffeine Version: 0.3.12

**Comment by mikebronner** [comment] 2017-12-05 15:17
I'm not sure I understand correctly: you mentioned that you logged out, yet expect to be able to continue using the session?

Caffeine for Laravel does not prevent you from being logged out, is prevents the session from timing out on certain forms.

Also, make sure you update to the latest version of the package: 0.5.0 or 0.4.2 (for Laravel 5.4).

**Comment by kurtssmith** [comment] 2017-12-05 15:29
I am new to Laravel, so please excuse my ignorance on this.  Here is my issue, the logout is redirected to the login page.  if I sit on the login page for a while and I try to login I get the error described above.  So then to login I have to click the Back button on my browser to go get rid of the error page which goes back to the login page hit refresh, the page then reloads I then put in my login credentials and I am successfully logged in again.   

So yes my problem is really on the login page if it sits for a while without logging in I get the VerifyCsrfToken.php error when I try to login.  

I have Laravel 5.4 but my php version is 5.6.15 and according to the documentation for laravelcaffeine  you need PHP 7 for LaravelCaffeine 0.4.X and I can't upgrade to PHP 7 for business reasons

**Comment by mikebronner** [comment] 2017-12-05 15:31
If you disable Caffeine for Laravel, do you experience the same issue?

**Comment by kurtssmith** [comment] 2017-12-05 16:04
Well it acts the same before and after I installed the package, so I don't know if it is actually working but it behaves as if it is not working

**Comment by mikebronner** [comment] 2017-12-05 16:11
In that case, it has nothing to do with Caffeine for Laravel, but is actual intended behavior of how Laravel works. The user is expected to refresh the login page. I will go ahead and close this for now, but please do let me know if you experience any issues with Caffeine in the future. :) Thanks for reaching out :) always better to be safe and check.

**Closed by mikebronner** 2017-12-05 16:11 UTC
