### ISSUE TITLE
url() function in the config file breaks artisan

### ISSUE THREAD

**Issue by Smiley01987** [GeneaLabs/laravel-caffeine#42] opened 2016-09-29 13:06 UTC
The url function inside the generated config file breaks the artisan command.

Laravel Framework version 5.1.31 (LTS)

Stacktrace:

Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /Users/xxx/Documents/xxx/xxx/xxx/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /Users/xxx/Documents/xxx/xxx/xxx/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 102

Call Stack:
0.2623    3296608   8. url() /home/vagrant/xxx/xxx/xxx/config/genealabs-laravel-caffeine.php:5

**Comment by mikebronner** [comment] 2016-09-29 13:49
Duplicate of #39. This is already resolved and the readme updated, please update your config file accordingly. (Thanks non-the-less for reporting it!) :)

**Closed by mikebronner** 2016-09-29 13:49 UTC
