### ISSUE TITLE
Vue.js @click events not working after installing 7.0

### ISSUE THREAD

**Issue by JoshMountain** [GeneaLabs/laravel-caffeine#123] opened 2020-03-05 21:33 UTC
## Expected Behavior
`@click` fires when elements are clicked.

## Actual Behavior
After installing, any `@click` fired from within a form seems to disappear. The event never fires. Is anyone else running into this?

## Environment
- PHP Version: 7.4.
- Laravel Version: 7.0.4
- LaravelCaffeine Version: 7.0

**Comment by mikebronner** [comment] 2020-03-05 21:43
Thanks .. I have seen some of these issues as well. What version of Vue are you running? Also, do you have AlpineJS installed along with Vue?

**Comment by JoshMountain** [comment] 2020-03-05 22:10
We are not using Alpine.

Vue version is 2.6.11

Thanks!

**Comment by JoshMountain** [comment] 2020-03-10 16:30
@mikebronner Any progress on this? Unfortunately we can't use Caffeine at the moment :(

**Comment by mikebronner** [comment] 2020-03-10 16:35
@JoshMountain your issue seems to be different than mine ... mine was due to a Due/Alpine conflict, and did not involve this package.

Can you post a minimal repo that reproduces the error? That will let me debug the problem more readily, since I am not seeing this issue in my projects at the moment.

**Comment by JoshMountain** [comment] 2020-03-11 01:21
@mikebronner Here is a [minimal repo that reproduces the error](https://github.com/JoshMountain/caffeine-demo). If you visit the `/` route you will see a page with a button and a counter. When you click the button nothing happens. However, if you run `composer remove GeneaLabs/laravel-caffeine` the counter works again.

Thanks!

**Comment by mikebronner** [comment] 2020-03-11 15:10
@JoshMountain Awesome! Thanks or getting that prepped. I'll take a look at it right now.

**Comment by mikebronner** [comment] 2020-03-11 17:07
@aglipanci Can you give release 7.0.2 a try and let me know how it works? Closing for now, pending feedback. :)

**Closed by mikebronner** 2020-03-11 17:07 UTC
Labels: unconfirmed bug

**Comment by JoshMountain** [comment] 2020-03-11 22:06
Looks like that did the trick! Thank you for the fast work @mikebronner :)
