### ISSUE TITLE
Feature request: specify specific routes for session preservation

### ISSUE THREAD

**Issue by marcelgruber** [GeneaLabs/laravel-caffeine#45] opened 2016-10-10 16:58 UTC
One problem I ran into is that my app has many forms throughout which has the effect of preserving a session indefinitely. I would like to be able to, in the configuration, specify pages in which drip can be applied to. I will likely do a pull request for this in the next few weeks. Cheers!

**Comment by mikebronner** [comment] 2016-10-10 21:24
Hi @marcelgruber -- would you consider being able to specify which form cause the drip to take effect in, for example:
```html
<form data-drip="true">
```

I have been pondering this problem as well, as it applies to other situations (like the logout post form in Laravel 5.3).

The reason I like this solution than just doing it for all forms is that it is explicit and intentional. Would this work for you?

~Mike

**Comment by marcelgruber** [comment] 2016-10-10 21:32
That would actually be perfect.




On Mon, Oct 10, 2016 at 3:24 PM -0600, "Mike Bronner" <notifications@github.com> wrote:












Hi @marcelgruber -- would you consider being able to specify which form cause the drip to take effect in, for example:

<form data-drip="true">



I have been pondering this problem as well, as it applies to other situations (like the logout post form in Laravel 5.3).



The reason I like this solution than just doing it for all forms is that it is explicit and intentional. Would this work for you?



~Mike

**Comment by ItaloBC** [comment] 2017-12-09 22:54
Personally I think is a good idea to add Caffeine as a kind of `middleware` inside the `Route` configuration, like this:

````php
Route::namespace('Public')
    ->name('public')
    ->middleware('caffeine-drip')
    ->group(function () {

        // ...

        Route::get('myFormWithoutDrip')
            ->middleware('caffeine-drip:exclude');

        });

Route:get('thisFormMustHaveDrip')
    ->middleware('caffeine:explicit')

````

Let's break it down:

* `caffeine-drip`: make Caffeine look for forms with `csrf_token` automatically and apply the script. This is the default behavior.
* `caffeine-drip:exclude`:  Exclude Caffeine from adding the script here, whether or not has a form with `csrf_token`. This can only be used under a Route group with the `caffeine-drip` middleware.
* `caffeine-drip:explicit`: Add the Caffeine script regardless of the page content - even if it doesn't have a form with `csrf_token`. . This option should override the `caffeine-drip` middleware behavior, as it tells it to apply the script forcefully.

**Comment by mikebronner** [comment] 2017-12-09 23:05
Caffeine actually is already a middleware. It might be easiest to make it implementable as a route middleware as well. Unfortunately that is not something that can be automatically registered, so it would require some manual work. By default it would remain a global middleware, unless switched to a route middleware in the configuration. Thoughts?

**Comment by ItaloBC** [comment] 2017-12-09 23:13
Seems that can be [automatically registered](https://laracasts.com/discuss/channels/general-discussion/register-middleware-via-service-provider/replies/311164). For what I see, [`Illuminate\Routing\Route` has the implementation to register an alias for the middleware](https://laravel.com/api/5.5/Illuminate/Routing/Router.html#method_aliasMiddleware).

**Comment by mikebronner** [comment] 2017-12-09 23:18
The problem is regeistering in middleware groups ... I will take a look. (Not today though.)

**Comment by mikebronner** [comment] 2017-12-11 03:55
0.6.1 (soon to be released, just waiting for checks to pass) from PR #75 will have a way to disable drips on any given page via a meta tag on the page.

Will be adding route middleware on the next release (0.6.2), perhaps in a week or two, as I can get to it.

**Comment by mikebronner** [comment] 2017-12-12 02:17
Version 0.6.2 (to be released in a few minutes) will contain route-middleware functionality.

**Closed** 2017-12-12 02:16 UTC
Labels: enhancement
