### ISSUE TITLE
Routes completely broken after uninstall

### ISSUE THREAD

**Issue by SirPurpleness** [GeneaLabs/laravel-caffeine#64] opened 2017-06-16 11:44 UTC
Laravel doesn't seem to be using any routes in /routes anymore, everything returns error 404 not found after I removed this.

config/app.php has been updated accordingly but nothing seem to fix this.

**Comment by mikebronner** [comment] 2017-06-16 12:51
@SirPurpleness I'm not sure what you mean. Can you provide a stack trace of the error? If you removed your routes file, I wouldn't think that has anything to do with this package? Why do you think Caffeine is the cause of the issue?

**Comment by SirPurpleness** [comment] 2017-06-16 12:57
I think this Caffeine is the issue as it changes the default web.php route that Laravel uses, as any changes I make to my routes/web.php have no effect on Laravel whatsoever. There's not much of a stack trace either, it only returns "NotFoundHttpException" as seen here http://prntscr.com/fki6f5 (so there's no error logs about it other than that).

**Comment by mikebronner** [comment] 2017-06-16 13:13
This seems more like you don't have the routes file properly configure in laravel. What is the URL you are trying to access when you get the notfoundhttpexception?

Also, please provide the following information:

Laravel Version (check composer.lock file)
PHP Version (check homestead, not the Mac)
Caffeine Version (check composer.lock file)

**Comment by SirPurpleness** [comment] 2017-06-16 13:38
All urls return notfoundhttpexception.

This is on a new install, and my routes worked before I came across Caffeine. If I use the route in (vendor\genealabs\laravel-caffeine\routes) then it does work, but if I remove Caffeine the /routes/web.php no longer works, so I can't see how my Laravel isn't properly configured.

Using 0.4.2 of Caffeine and Laravel 5.4.25.

**Comment by mikebronner** [comment] 2017-06-16 13:41
if all URLs return not found exceptions, that means your regular routes file is not being loaded.

**Comment by SirPurpleness** [comment] 2017-06-16 13:44
Yes, obviously. Then how come they are not being loaded after uninstalling Caffeine? Seems a bit odd to me. I did a fresh install of Laravel on a VPS of mine (worked well), and then transferred all files from /app, /config, /public, /resources and /routes and it instantly returns the same error. I checked all files it uploaded and can't find out what's wrong. So Caffine must have done something to my Laravel.

**Comment by mikebronner** [comment] 2017-06-16 13:51
I think the removal of caffeine and your routes not working is a coincidence. My best guess at this point is that you have a configuration problem in one of your config files, or perhaps in the `Kernel.php` class. Without more concrete information as to exactly how this is caused by caffeine there is unfortunately not much more I can do. Caffeine does not alter any code of your app, so if you have completely removed caffeine, I don't see how it can be the cause here.

My recommendation would be to debug the bootstrapping sequence of you app where the routes should be loaded, and see if anything unexpected is happening.

**Comment by SirPurpleness** [comment] 2017-06-16 14:02
I can replace Kernel.php with the default one, and the config files, there's no difference. A thing I discovered though was that my changes to RouteServiceProvider.php has no effect as well.

**Comment by mikebronner** [comment] 2017-06-16 14:05
Start with a clean, brand new project. Verify that it works before doing anything. Then bring over your changes one at a time. Test after each change. That will tell you where something is broken.

**Comment by mikebronner** [comment] 2017-06-27 14:47
Closing for now. Please re-open if issue persists.

**Closed by mikebronner** 2017-06-27 14:47 UTC
Labels: unconfirmed bug

**Comment by aurawindsurfing** [comment] 2019-04-10 16:05
Hi! I have removed the package and seem to have a similar issue.

removed from composer, done composer dump-autoload

```
php artisan route:list
```

does not show it as well

I have understand.io installed however and I can see that something is still trying to access:

```
/genealabs/laravel-caffeine/drip
```

which in turn produces

```
Symfony\Component\HttpKernel\Exception\NotFoundHttpException
```

Any ideas what can cause that issue?

**Comment by mikebronner** [comment] 2019-04-10 16:10
@aurawindsurfing Have you tried
```sh
php artisan cache:clear
php artisan route:clear
```
