### ISSUE TITLE
All Views are rendered twice

### ISSUE THREAD

**Issue by lbausch** [GeneaLabs/laravel-caffeine#7] opened 2015-08-30 21:00 UTC
This is because calling `$content->render();` in `LaravelCaffeineDripMiddleware.php` on line 28.
I noticed this behaviour because in one of my Views I use `Session::pull()`. The data are pulled during the first rendering and of course no longer available when the View is rendered the second time (and delivered to the client).

Any suggestions to avoid this?

**Comment by mikebronner** [comment] 2015-08-30 21:08
I will look into the possibility of injecting the output without rendering in the middleware, but passing it on. Any suggestions on how to do this are welcome. :) I initially tried to figure something out, but ended up spending too much time on it, without finding a solution.

**Comment by lbausch** [comment] 2015-09-01 17:36
Thank you for your quick reply. I don't have a clever idea neither - otherwise I would have created a pull request.

**Comment by mikebronner** [comment] 2015-09-02 23:21
@lbausch can you paste the code snippet where you execute the Session::pull() with the relevant bits, as well as past your `/app/Http/Kernel.php` file content here as well? I will try to recreate the issue on my end to see if something can be figured out.

Thanks :)

**Comment by lbausch** [comment] 2015-09-05 10:36
Sure, check this repository (https://github.com/lbausch/laravel-caffeine-test) for a demonstration. :)

**Comment by mikebronner** [comment] 2015-09-05 14:16
@lbausch thanks for throwing up an example :) much appreciated. I am pretty busy today, but will look at it this evening.

**Comment by mikebronner** [comment] 2015-09-07 15:37
Hi @lbausch I took a look at the test repo, and ran it without causing duplications. Would be happy to do a ScreenHero session with you do look at what's happening. Please email me directly if you would like to troubleshoot that way (email is in profile). :)

**Comment by gavinbenda** [comment] 2016-03-23 00:49
Interesting issue, maybe there could be a 'manual' mode so a blade include file could just be used rather than via middleware (perhaps the 'automated injection' of the code controlled on/off by route groups).

I'm having an issue using Former (https://github.com/formers/former) as it automatically generates fields on render, however because this gets rendered twice, it will calculate names of form elements twice (i.e. name becomes name2).

**Comment by mikebronner** [comment] 2016-06-16 03:04
I have a possible fix for this. Will try it out this weekend.

**Comment by mikebronner** [comment] 2016-06-18 15:53
Update: sorry, no dice at the moment. I was hoping to hook into a view rendered event, but there doesn't seem to be one. I would consider filing a bug report with the packages that have these issues.

From a macro perspective, any package shouldn't be susceptible to the number of times a page is pre-rendered before it is output to the browser. While I would have liked to be able to find a work-around, I don't think this is a bug or bad methodoligy in this package, so I will close this issue for now.

Please re-open it if you find a possible solution, or you see an increase in occurrence of this issue with multiple other packages.

**Comment by nfauchelle** [comment] 2016-09-10 02:41
I just ran into this issue, took me a little bit of hunting to pin it down to caffeine!

What I would suggest is two install methods.
1 - Use the Middleware as current.
2 - Manual insertion of something like {!! insert_caffeine_drip() !!} in page body above the </body>

Doing this would be quite straight forward (roughly)
* Extract out the generation of the javascript to the Helper class in the package
* Make it so the javascript checks for _token tags instead of PHP
* Update the middleware to use that helper
* Setup a function like {!! insert_caffeine_drip() !}} which calls the helper, or just make it so the helper method can be called statically.

Sure it's not AS nice as relying all on the Middleware, but it's a viable alternative until a better solution comes along.

Thoughts?

**Comment by mikebronner** [comment] 2016-09-12 15:54
Thanks for the update on this, Nick. If you could provide a working demonstration of the issue with a test repo, that would be great. I have not yet been able to replicate this, or have someone provide a working example of this issue.

**Comment by nfauchelle** [comment] 2016-09-13 11:08
@mikebronner 
Sure, I can reproduce it with this:

- composer create-project --prefer-dist laravel/laravel caffeine-test
- cd caffeine-test
- composer require genealabs/laravel-caffeine:~0.3.0
- edit config/app.php for the Service Provider
- edit the app/Http/kernel.php for the Middleware
- edit resources/views/welcome.blade.php, append ```<?php \Log::info('Rendered welcome') ?>``` to bottom of view
- open page in browser, see the Laravel 5 welcome page
- check storage/logs/laravel.log, two entries for _Rendered welcome_ are visible.

Note; This installed 5.2.31 for me since I am running php 5.5 on the command line.

**Comment by jwondrusch** [comment] 2016-09-16 00:48
Can confirm we're encountering this also.  It causes errors when pulling information from session such as errors or alerts we've got stored there.  @nfauchelle has a good test case.

**Comment by mikebronner** [comment] 2016-09-24 23:48
This should now be fixed in version 0.4.0. I haven't had time to specifically test this issue, but could you guys give it a go and let me know? Thanks! :) Closing for now, please re-open if you still see this issue.

**Closed** 2016-09-24 23:47 UTC
Labels: low priority, unconfirmed bug

**Comment by nfauchelle** [comment] 2016-09-25 01:11
@mikebronner 
Was set to test it, but it now requires PHP7, so I cant jump to 0.4.0...

If I modify my 
```vendor/genealabs/laravel-caffeine/src/Http/Middleware/LaravelCaffeineDripMiddleware.php``` based on https://github.com/GeneaLabs/laravel-caffeine/commit/be1bc135e735745f27e89fe13e28838c1451c358 then the issue is fixed. So I guess I can just make my own Middleware for the fix.

Thanks.

**Comment by mikebronner** [comment] 2016-09-25 01:16
Give me a sec, I will make a 0.3.12 version just for you. :)

**Comment by mikebronner** [comment] 2016-09-25 01:25
ok, try installing 0.3.12 ... let me know how it goes.

**Comment by nfauchelle** [comment] 2016-09-25 01:30
Thanks, thats fixed :-)
