### ISSUE TITLE
call url() helper in config file.

### ISSUE THREAD

**Issue by idoooooo** [GeneaLabs/laravel-caffeine#62] opened 2017-04-17 07:33 UTC
due to default $domain always 'null'
$domain = config('genealabs-laravel-caffeine.domain', url('/'));

and you have to set
"domain" => url('/')

will cause the artisan error like:

[Symfony\Component\Debug\Exception\FatalThrowableError]                                                              
  Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\H  
  ttp\Request, null given, called in /..../vendor/laravel/framewo  
  rk/src/Illuminate/Routing/RoutingServiceProvider.php on line 64

do this for fix the error.

return [
    'dripIntervalInMilliSeconds' => 300000, // every 5 minutes
    'domain' => PHP_SAPI === 'cli' ? null : url('/'), // defaults to url('/')
    'route' => 'genealabs/laravel-caffeine/drip', // can be customized
];

Laravel 5.4

**Comment by jass-trix** [comment] 2017-05-16 01:23
what will be caused by that change?
is there any difference?

**Comment by idoooooo** [comment] 2017-05-16 14:26
route will not found if site is not in root directory.

**Comment by mikebronner** [comment] 2017-05-16 23:37
Thanks gifs, sorry for dropping the ball on this one. Looking into it now. @idoooooo was your comment geared toward @jass-trix , or is that an issue you have discovered?

**Comment by mikebronner** [comment] 2017-05-16 23:50
@idoooooo can you provide a complete stack trace and indicate what steps you took to trigger it, so I can reproduce? Thanks!

**Comment by maikealame** [comment] 2017-06-13 20:08
Same error here !
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\H
ttp\Request, null given, called in /..../vendor/laravel/framewo
rk/src/Illuminate/Routing/RoutingServiceProvider.php on line 60
```
And this my config
`'domain' => env("APP_URL",url('/')),`

My routes
`Route::get('/', ['as'=>'/','uses'=>'HomeController@index']);`

**Comment by mikebronner** [comment] 2017-06-14 16:05
@maikealame unfortunately Laravel 5.2 is no longer supported with this plugin. You need to make sure to follow the 5.2 readme provided in the installation section. If you did that and it still doesn't work, I'm afraid the only suggestion I can offer is upgrading to Laravel 5.3 or 5.4.

Looking at your error above, I would wager it is not directly related to Caffeine, but something else interfering.

Regarding the above commend by @idoooooo that it doesn't work if the Laravel app is not in the domain root directory, I'm not sure how to address that. I have never used a Laravel app with it not being in the root. The only suggestion I might have is setting the `domain` config variable to point to where Laravel runs.

**Comment by mikebronner** [comment] 2017-06-27 14:48
Closing for now. Please open a new issue if this persists (one for each topic, we were getting two different issues going on here).

**Closed by mikebronner** 2017-06-27 14:48 UTC
Labels: unconfirmed bug
