### ISSUE TITLE
Laravel 6.0 and 6.1 Support

### ISSUE THREAD

**Issue by darkperis** [GeneaLabs/laravel-caffeine#116] opened 2019-10-07 13:39 UTC
Please add support for Laravel 6.1

**Comment by mikebronner** [comment] 2019-10-07 14:00
Should be supported. What composer error are you getting?

**Comment by rjsworking** [comment] 2019-10-07 15:54
I think the problem is ```jenssegers/model``` needs to be tagged with a new version.
Cheers

**Comment by mikebronner** [comment] 2019-10-07 16:46
@rjsworking  Yea, that's definitely holding some of my projects up as well. I believe the necessary changes have been merged. Waiting for a release.

**Closed by mikebronner** 2019-10-07 16:46 UTC
Labels: unconfirmed bug

**Comment by rjsworking** [comment] 2019-10-07 17:14
@mikebronner The workaround is fork the ```jenssegers/model``` package, update it's composer json to support L6.1 and use it in your projects/packages composer.json: "jenssegers/model": "dev-master".

**Comment by mikebronner** [comment] 2019-10-08 17:42
@rjsworking This should now be fixed in 1.0.3. Please let me know how that works for you.

**Comment by mikebronner** [comment] 2019-10-08 17:54
Try 1.0.4 ... made a mistake in pushing 1.0.3. Sorry about that.

**Comment by rjsworking** [comment] 2019-10-08 21:22
Np. It's working. 
Thank you very much.
