### ISSUE TITLE
ServiceProvider path and middlewareGroupExists() error

### ISSUE THREAD

**Issue by jcornil** [GeneaLabs/laravel-caffeine#40] opened 2016-09-27 11:26 UTC
Right after the installation of 5.3, I got "ServiceProvider not found" error.

Class 'GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider' not found

I guess service provider path and file name has been changed to...

GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService::class,

right?

But, when I change the path and file name, I get type error.

Type error: Return value of GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService::middlewareGroupExists() must be of the type boolean, null returned

**Comment by mikebronner** [comment] 2016-09-27 13:12
Thanks for reporting this. :) This sounds like an error from a dev-master version ... do you have version 0.4.0 installed?

**Comment by jcornil** [comment] 2016-09-27 13:35
Yes, I have version 0.4.0.

**Comment by mikebronner** [comment] 2016-09-27 13:37
My appologies for the problems. I am looking into that straight away and should have a fix, if I can reproduce it, within the next 30 mins.

**Comment by mikebronner** [comment] 2016-09-27 13:52
can you do me a favor and paste the content of the following file here: `/vendor/genealabs/laravel-caffeine/src/Providers/LaravelCaffeineService.php`? I am currently unable to reproduce the issue and want to verify that your code looks the same as mine. :)

**Comment by jcornil** [comment] 2016-09-27 13:57
Sure...

<?php namespace GeneaLabs\LaravelCaffeine\Providers;

use GeneaLabs\LaravelCaffeine\Http\Middleware\LaravelCaffeineDripMiddleware;
use Illuminate\Support\ServiceProvider;

class LaravelCaffeineService extends ServiceProvider
{
    protected $defer = false;

    public function boot()
    {
        app('router')->group($this->middlewareGroupExists('web')
            ? ['middleware' => 'web']
            : [], function () {
                require __DIR__ . '/../../routes/web.php';
            });

        $this->publishes([__DIR__ . '/../../config/genealabs-laravel-caffeine.php' => config_path('genealabs-laravel-caffeine.php')], 'genealabs-laravel-caffeine');
    }

    public function register()
    {
        $this->mergeConfigFrom(__DIR__ . '/../../config/genealabs-laravel-caffeine.php', 'genealabs-laravel-caffeine');

        app('Illuminate\Contracts\Http\Kernel')->pushMiddleware('\GeneaLabs\LaravelCaffeine\Http\Middleware\LaravelCaffeineDripMiddleware');
    }

    public function provides() : array
    {
        return ['genealabs-laravel-caffeine'];
    }

    private function middlewareGroupExists(string $group) : bool
    {
        $routes = collect(app('router')->getRoutes()->getRoutes());

        return $routes->reduce(function ($carry, $route) use ($group) {
            $carry = $carry ?? false;
            $actions = (array) $route->getAction();

            if (array_key_exists('middleware', $actions)
                && in_array($group, (array) $actions['middleware'])
            ) {
                return true;
            }

            return $carry;
        });
    }
}

**Comment by mikebronner** [comment] 2016-09-27 14:01
That all looks right ... I'm baffled ... do you have a `/config/genealabs-laravel-caffeine.php` file by any chance? Could you delete that and try again?

**Comment by jcornil** [comment] 2016-09-27 14:03
No, I don't have that file published.

**Comment by mikebronner** [comment] 2016-09-27 14:09
Ah! I found the problem, fix is incoming. For some reason it does not find your routes (probably an upgrade issue).

**Comment by mikebronner** [comment] 2016-09-27 14:12
0.4.1 released. It should be available for composer update any minute. Let me know if that works -- if you have any issues, please reopen. :) Thanks for reporting this!

**Closed** 2016-09-27 14:12 UTC
Labels: high priority, unconfirmed bug

**Comment by jcornil** [comment] 2016-09-27 14:17
Yeah~ now it works. Thanks. :)
